version: '3'
services:
  db:
    image: mongo
    restart: always
    container_name: toxicity_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kU+fPT8&tGgz]fEh
    ports:
      - "27018:27017"
    networks:
      - toxicity_net
  backend:
    build: 
      dockerfile: /src/main/docker/Dockerfile.jvm
    restart: always
    environment:
      - QUARKUS_MONGODB_DATABASE=toxic_annotation
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://root:kU%2BfPT8%26tGgz%5DfEh@toxicity_db:27017
      - QUARKUS_HTTP_CORS_ORIGINS=*
      - QUARKUS_HTTP_PORT=8082
    networks:
      - toxicity_net
    container_name: toxicity_backend
    ports:
      - "8082:8082"
    depends_on:
      - db
  frontend:
    build: 
      context: ./src/main/webapp/
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=8081
      - BACKEND_URL=http://localhost:8082
    ports:
      - "8081:8081"
    expose:
      - 8081
    volumes:
      - '/app/node_modules'
    container_name: toxicity_frontend
    networks:
      - toxicity_net
    depends_on:
      - backend
networks:
  toxicity_net:
    internal: false
